### ISSUE TITLE
Need A Logo

### ISSUE THREAD

**Issue by JohnMarzulli** [JohnMarzulli/StratuxHud#15]
For the purpose of webpages, the Repo, and communications StratuxHud should have a logo.

The logo should be in an icon size, a larger 256x256 size, and possibly in a banner size.

**Comment by mrdoornbos** [comment]
Got any thoughts on a direction? influences? Hard to just do one from nothing, but if you have some thoughts on it I can whip something up.

**Comment by JohnMarzulli** [comment]
@mrdoornbos  & @kipbmock  - Do you have any ideas?

I made some "programmer art"  with media/hud_logo.png

**Comment by kipbmock** [comment]
Yeah, I actually do. I'm pretty swamped at work right now, but if we worked out some sort of compensation I'd be happy to get you a logo. How about I send over a contract that just gives me the copyright to whatever I send you, and if you like it, you can pay me.

**Comment by JohnMarzulli** [comment]
Shipped in 1.5
