### ISSUE TITLE
Hudly Classics are no longer available

### ISSUE THREAD

**Issue by kurtjohnson0** [JohnMarzulli/StratuxHud#29]
Now what?

**Comment by JohnMarzulli** [comment]
Thank you for bringing that to my attention.

This is going to take some research.

**Comment by JohnMarzulli** [comment]
@kurtjohnson0  - I have ordered a 2nd Gen Kivic.

It is supposed to arrive tomorrow. I'll let you know what happens.

**Comment by JohnMarzulli** [comment]
Have received and validated compatibility with a Kivic HUD 2nd Gen

**Comment by brantel** [comment]
How does the Kivic communicate with the system without a HDMI port?

**Comment by N129BZ** [comment]
The readme has this info:

https://www.amazon.com/gp/product/B008R39FKS/ref=ppx_yo_dt_b_asin_title_o01__o00_s00?ie=UTF8&psc=1
