### ISSUE TITLE
Add Configuration setting for speed precision

### ISSUE THREAD

**Issue by N129BZ** [JohnMarzulli/StratuxHud#32]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by N129BZ** [comment]
I made copies of configuration.py, config.json, and units.py to incorporate a new setting named "speed_precision": which allows you to set the precision of the displayed speed to whatever you want. I wanted to suppress the constantly changing decimal value of speed because it might be distracting.  I implemented that in units.py with the following (new in 3.6) literal interpolated string statement:

**return f"{distance / feet_to_sm:.{precision}f} {UNIT_LABELS[STATUTE][unit_type]}"**

Not sure if anyone would want this but if so, it's potentially available.

**Comment by JohnMarzulli** [comment]
Will be addressed by https://github.com/JohnMarzulli/StratuxHud/tree/1.4_beta
