### ISSUE TITLE
String Interpolation Not Supported In Python 3.5

### ISSUE THREAD

**Issue by JohnMarzulli** [JohnMarzulli/StratuxHud#36]
**Describe the bug**
Setup instructions can not be completed with Python 3.5.

The `f"{value}"` syntax does not work with Python3.5/Raspbian

**To Reproduce**
python3 setup.py develop

**Comment by N129BZ** [comment]
I'm looking at what it takes to create a downloadable IMG file so the os + app can be done just like Stratux does.  Download the img, burn the sd card, done.

**Comment by JohnMarzulli** [comment]
Thanks, but I think you meant that for the other issue.

Related, I am trying to bootstrap the HUD using Raspbian Lite, which will drastically cut down the image size.
