### ISSUE TITLE
Artificial Horizon & Roll Indicator Improvements.

### ISSUE THREAD

**Issue by JohnMarzulli** [JohnMarzulli/StratuxHud#41]
The pitch and roll ladder could be more readible.

To clear up space, a new roll indicator that uses radial lines (like a Dynon) should be created, and made the default, while keeping the current text of the pitch and roll as an optional element.

**Comment by RickMason1** [comment]
I think your upgrade would really by useful

**Comment by JohnMarzulli** [comment]
Major revisions to the graphics of the roll indicator in V1.5
