### ISSUE TITLE
Cold build Trouble

### ISSUE THREAD

**Issue by RickMason1** [JohnMarzulli/StratuxHud#54]
John,
I've been trying to do a full build from scratch by downloading noobs, the stratux, then stratuxhud.

The problem seems to be at the entry:
python --version. Verify that your version is 2.7.14

I'm at python  2.7.13.  The build bites the dust soon after this.

I tried downloading   8GB microsd card:
https://github.com/JohnMarzulli/StratuxHud/releases/tag/v1.5 

But can't figure out how to combine v1.5 image with the stratux image.

Rick Mason

**Comment by JohnMarzulli** [comment]
I have Stratux + 1.5 running.

Expect an image in a few days.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by JohnMarzulli** [comment]
@RickMason1  - I have uploaded a Stratux + HUD image of 1.5 for Pi 3B. Please note that the Stratux (receiver) will not run on a 3B+, only on a 3.

**Comment by saabnut** [comment]
Thank You!

On Thursday, August 1, 2019, John Marzulli <notifications@github.com> wrote:
> @RickMason1 - I have uploaded a Stratux + HUD image of 1.5 for Pi 3B.
Please note that the Stratux (receiver) will not run on a 3B+, only on a 3.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/ufCk8ZgnTk4roPk4kiSAA5ROol-ckNHfO0PkF2xAnxNDfQP0xof7X4xSWvaOKDvyqWzh11-44sn3MQymvALgaiYXK0HmgVYgTOeZIv-cVXRALS9DnkXc9AwR9aHdmDXWFyMOH27LOOoIVDn3NaZbCYtqrNQ_TfQH_sVGxcg4ORQJUvBWo5F1Ut_3TiUnsOUGDV1hWeG9eE7s3o5l_w-OC6HnvbxjnHm5bNn6Dpd9PQ=s0-d-e1-ft#https://github.com/notifications/beacon/AHAT66GFZ3IKAMB2UDKKDULQCKF6LA5CNFSM4IGWI66KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3JTIRY.gif>

**Comment by JohnMarzulli** [comment]
@RickMason1  - Have you been able to try any of the image files yet?

**Comment by RickMason1** [comment]
John,
Success.  The AIO did it,

Thanx
Rick
