### ISSUE TITLE
UTC Time using System Time Instead of GPS

### ISSUE THREAD

**Issue by Michaelc136** [JohnMarzulli/StratuxHud#58]
**Describe the bug**
UTC Time using System Time instead of GPS

**To Reproduce**
Navigating to the Universal Time window StratuxHUD is only using the system time on 1.6.0

**Additional context**
I appreciate all the help!

**Comment by JohnMarzulli** [comment]
System time is used ONLY when the GPS is unable to provide a reliable time.
