### ISSUE TITLE
Traffic Not Reporting Correctly

### ISSUE THREAD

**Issue by Michaelc136** [JohnMarzulli/StratuxHud#59]
**Describe the bug**
To be more specific Traffic is reporting distance within the limits of 1.0 NM (and SM) to max of about 15 NM (and SM),
None of the distances are correct. 

for some reason its not reporting the accurate NM or SM info from the Stratux Unit even when SM are below 15NM

**Screenshots**
![image](https://user-images.githubusercontent.com/62223909/77218860-4d5ae600-6b06-11ea-954e-b611f1c6e940.png)
![image](https://user-images.githubusercontent.com/62223909/77218867-58157b00-6b06-11ea-8863-dbae9396cc29.png)
![image](https://user-images.githubusercontent.com/62223909/77218872-6368a680-6b06-11ea-9dd4-bd8abd509167.png)

Three images, One of which shows my Foreflight, Stratux window, and finally the HUD window. **Just to confirm!!! ForeFlight and Stratux were reporting the same distances I just couldn’t screenshot fast enough during the window switch.**

**Additional context**
I did some snooping around in the code with my limited understanding. I do believe the haversine formula is correct, just was confused about the "/" in the middle, unsure if that was meant to be a line break.

I ended up making a gitclone to experiment and tried 
math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2

Via (cd /home/pi/StratuxHud/traffic.py)
nano edit

different formatting no effect, as expected,

Regardless, not complaining, everything else is great, thanks John.

**Comment by JohnMarzulli** [comment]
Will be addressed by #61
